[package]
name = "rust_utils"
version = "0.6.0"
authors = ["Sebastian Kaźmierczak <moques93@gmail.com>"]
edition = "2021"

[dependencies]
config = { version = "0.13.3", default-features = false, features = [] }
serde = { version = "1.0.162", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.96", default-features = false, features = ["std"] }
log = { version = "0.4.17", default-features = false, features = [] }
dotenv = { version = "0.15.0", default-features = false, features = [] }
envmnt = { version = "0.10.4", default-features = false, features = [] }
itertools = { version = "0.10.5", default-features = false, features = [] }
slugify = { version = "0.1.0", default-features = false, features = [] }
num = { version = "0.4.0", default-features = false, features = [] }
