[package]
name = "rust_utils"
version = "0.2.0"
authors = ["Sebastian Kaźmierczak <moques93@gmail.com>"]
edition = "2021"

[dependencies]
config = "^0.13.3"
serde = {version = "^1.0.152", features = ["derive"]}
log = "^0.4.17"
dotenv = "^0.15.0"
envmnt = "^0.10.4"
itertools = "^0.10.5"
slugify = "^0.1.0"
num = "^0.4.0"

[dev-dependencies]
pretty_assertions = "^1.3.0"
mockall = "^0.11.3"

[build-dependencies]
